import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useStore } from '../contexts/StoreContext';
import { cartApi } from '../services/cartApi';
import { Button, ConfirmDialog, EmptyState, ErrorState, Media, PageHeader, Price, Quantity, Skeleton } from '../components/storefront/UI';
export default function Cart() {
  const { cart, pending, mutate } = useStore();
  const [confirm, setConfirm] = useState(null);
  const invalid = cart.data?.items.some(i => i.isOutOfStock || i.quantity > i.productStock);
  return <div className="s-container s-page"><PageHeader eyebrow="Your selection" title="Shopping cart"/>{cart.loading ? <Skeleton count={2}/> : cart.error ? <ErrorState error={cart.error} retry={cart.reload}/> : !cart.data?.items.length ? <EmptyState title="A little room for something lovely.">Your cart is empty. Find a new favourite in the shop.</EmptyState> : <div className="s-commerce-layout"><div><div className="s-cart-items">{cart.data.items.map(item => <article className="s-cart-item" key={item.id}><Link to={`/products/${item.productId}`}><Media src={item.productImageUrl} alt={item.productName}/></Link><div><h2><Link to={`/products/${item.productId}`}>{item.productName}</Link></h2><p><Price value={item.productPrice}/> each</p>{(item.isOutOfStock || item.quantity > item.productStock) && <p className="s-error-text" role="alert">{item.isOutOfStock ? 'No longer available. Please remove this item.' : 'Availability changed. Please reduce the quantity.'}</p>}<Quantity label={`Quantity for ${item.productName}`} value={item.quantity} max={item.productStock} disabled={pending || cart.loading || item.isOutOfStock} onChange={quantity => mutate(() => cartApi.updateCartItem(item.id, quantity), cart.reload)}/><Button variant="text" disabled={pending} onClick={() => setConfirm(item)}>Remove</Button></div><Price value={item.subtotal}/></article>)}</div><div className="s-actions"><Link className="s-text-link" to="/products">← Continue shopping</Link><Button variant="text" disabled={pending} onClick={() => setConfirm('all')}>Clear cart</Button></div></div><aside className="s-summary"><h2>Your order estimate</h2><div className="s-row"><span>{cart.data.totalItems} items</span><Price value={cart.data.total}/></div><p>Product subtotal only. Shipping and payment arrangements are not included in this estimate.</p>{invalid ? <p className="s-error-text">Resolve unavailable items before continuing.</p> : <Link className="s-button s-button-primary" to="/checkout">Continue to checkout →</Link>}</aside></div>}
    <ConfirmDialog open={!!confirm} title={confirm === 'all' ? 'Clear your cart?' : 'Remove this item?'} pending={pending} onClose={() => setConfirm(null)} onConfirm={async () => { if (await mutate(() => confirm === 'all' ? cartApi.clearCart() : cartApi.removeFromCart(confirm.id), cart.reload, 'Your cart has been updated.')) setConfirm(null); }}>{confirm === 'all' ? 'All items will be removed from your cart.' : confirm?.productName}</ConfirmDialog>
  </div>;
}
