import { test, expect } from '@playwright/test';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
// Opt-in, local-only real API smoke test. Fixture IDs contain no credentials.
const fixturePath = process.env.STOREFRONT_FIXTURE;
test('real customer lifecycle, catalogue, cart, wishlist, reviews, account and CMS', async ({ page, request }) => {
  test.skip(!fixturePath || !existsSync(fixturePath), 'Set STOREFRONT_FIXTURE to local QA fixture IDs.');
  test.setTimeout(600000);
  const fixture = JSON.parse(readFileSync(fixturePath!, 'utf8').replace(/^\uFEFF/, ''));
  const productId = fixture.products[0];
  const api = 'http://localhost:5197/api/v1';
  const suppliedCustomer = !!(process.env.STOREFRONT_CUSTOMER_EMAIL && process.env.STOREFRONT_CUSTOMER_PASSWORD);
  const email = process.env.STOREFRONT_CUSTOMER_EMAIL || `phase4-smoke-${Date.now()}@example.test`;
  const password = process.env.STOREFRONT_CUSTOMER_PASSWORD || `Qa4!${randomBytes(16).toString('hex')}`;
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  fixture.customerEmail = email; writeFileSync(fixturePath!, JSON.stringify(fixture));
  if (!suppliedCustomer) {
    await page.goto('./#/register');
    await page.getByLabel('Full Name', { exact: true }).fill('Phase4 QA Customer');
    await page.getByLabel('Email Address', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.getByLabel('Confirm Password', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Create Account', exact: true }).click();
    await expect(page).toHaveURL(/#\/login$/);
    const unconfirmed = await request.post(`${api}/auth/login`, { data: { email, password } });
    expect(unconfirmed.status()).toBe(401);
    const logBuffer = readFileSync('.runtime/api-runtime.log');
    const log = logBuffer.toString(logBuffer[0] === 255 ? 'utf16le' : 'utf8');
    const line = log.split('\n').findLast(line => line.includes(email) && line.includes('confirmation link'));
    const url = line?.match(/http[^\s]+/)?.[0];
    expect(!!url, 'Development confirmation link generated').toBe(true);
    const hash = new URL(url!).hash;
    await page.goto(`./${hash}`);
    await expect(page.getByRole('heading', { name: 'Email Verified' })).toBeVisible();
  }
  await page.goto(`./#/products/${productId}`);
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Phase4 QA print 01');
  await page.getByRole('button', { name: 'Add to cart', exact: true }).click();
  await expect(page).toHaveURL(/#\/login$/);
  await page.getByLabel('Email Address', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign In', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`#\\/products\\/${productId}$`));
  await page.reload(); await expect(page.getByRole('heading', { level: 1 })).toHaveText('Phase4 QA print 01');
  await page.getByRole('button', { name: 'View image 2', exact: true }).click();
  await expect(page.getByRole('button', { name: 'View image 2' })).toHaveAttribute('aria-pressed', 'true');
  await page.getByLabel('Product option').selectOption({ label: 'Large format' });
  await expect(page.locator('.s-pdp-info > .s-price')).toContainText('250.00');
  await expect(page.getByRole('button', { name: 'Add to cart', exact: true })).toBeDisabled();
  await page.getByLabel('Product option').selectOption('');
  await page.getByRole('button', { name: 'Increase quantity', exact: true }).click();
  await page.getByRole('button', { name: 'Add to cart', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Cart, 2 items', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Save to wishlist' }).click();
  await expect(page.getByRole('button', { name: 'Saved to wishlist' })).toHaveAttribute('aria-pressed', 'true');
  await page.locator('textarea[name="comment"]').fill('A temporary QA review to verify the customer flow.');
  await page.getByRole('button', { name: 'Save review', exact: true }).click();
  await expect(page.getByText('A temporary QA review to verify the customer flow.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit review' }).click();
  await page.locator('textarea[name="comment"]').fill('Updated QA review.');
  await page.getByRole('button', { name: 'Save review', exact: true }).click();
  await expect(page.getByText('Updated QA review.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Delete review' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click();
  await expect(page.getByText('Updated QA review.', { exact: true })).toHaveCount(0);
  await page.goto(`./#/products?categoryId=${fixture.category}`);
  await expect(page.locator('.s-product-card')).toHaveCount(12);
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await expect(page).toHaveURL(/page=2/); await expect(page.locator('.s-product-card')).toHaveCount(1);
  await page.getByLabel('Sort by').selectOption('price-desc');
  await expect(page).not.toHaveURL(/page=2/); await expect(page.locator('.s-product-card').first()).toContainText('Phase4 QA print 13');
  await page.getByRole('searchbox', { name: 'Search products', exact: true }).fill('no-such-qa-result');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'No products found', exact: true })).toBeVisible();
  await page.goBack(); await expect(page.locator('.s-product-card')).toHaveCount(12);
  await page.goto('./#/cart');
  await expect(page.getByRole('spinbutton')).toHaveValue('2');
  await page.getByRole('button', { name: /Increase quantity for/ }).click();
  await expect(page.getByRole('spinbutton')).toHaveValue('3');
  await expect(page.getByRole('link', { name: 'Cart, 3 items', exact: true })).toBeVisible();
  await page.goto('./#/wishlist');
  await page.getByRole('button', { name: 'Add to cart', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Cart, 4 items', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Remove', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Save something that feels like you.' })).toBeVisible();
  await page.goto('./#/profile'); await page.getByLabel('Full name', { exact: true }).fill('Phase4 QA Updated');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(page.getByText('Welcome, Phase4 QA Updated.', { exact: true })).toBeVisible();
  await page.goto('./#/addresses'); await page.getByRole('button', { name: 'Add an address' }).click();
  await page.getByLabel('Recipient name *', { exact: true }).fill('Phase4 QA Customer');
  await page.getByLabel('Address line 1 *', { exact: true }).fill('Temporary verification address');
  await page.getByLabel('City *', { exact: true }).fill('Colombo');
  await page.getByRole('button', { name: 'Save address', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Label *', { exact: true }).fill('QA address');
  await page.getByRole('button', { name: 'Save address', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'QA address', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Set default', exact: true }).click();
  await expect(page.getByText('Default', { exact: true })).toBeVisible();
  for (const width of [375, 430, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    for (const route of ['', `products?categoryId=${fixture.category}`, `products/${productId}`, 'cart', 'profile', 'addresses', 'orders', 'checkout']) {
      await page.goto(`./#/${route}`); await expect(page.locator('main h1')).toBeVisible();
      await expect(page.locator('main [aria-label="Loading content"]')).toHaveCount(0);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${route} at ${width}`).toBe(true);
    }
  }
  await page.goto(`./#/pages/${fixture.cmsSlug}`);
  await expect(page.getByText('Published content from the real CMS API.', { exact: true })).toBeVisible();
  await page.getByText('Is this real CMS content?', { exact: true }).click();
  await expect(page.getByText('Yes, this is a temporary verification page.', { exact: true })).toBeVisible();
  await page.goto('./#/checkout'); await page.getByLabel('Address', { exact: true }).fill('QA delivery address'); await page.getByLabel('City', { exact: true }).fill('Colombo'); await page.getByLabel('Postal code', { exact: true }).fill('00100');
  await page.getByRole('button', { name: 'Place order', exact: true }).click();
  await expect(page).toHaveURL(/#\/orders\/\d+$/);
  await expect(page.getByText('Your order has been placed. No online payment has been collected.', { exact: true })).toBeVisible();
  fixture.orderId = Number(page.url().split('/').at(-1)); writeFileSync(fixturePath!, JSON.stringify(fixture));
  await page.goto('./#/orders'); await expect(page.getByRole('link', { name: 'View order' })).toBeVisible();
  await page.goto('./#/addresses'); await page.getByRole('button', { name: 'Delete', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click(); await expect(page.getByRole('heading', { name: 'No saved addresses yet' })).toBeVisible();
  await page.goto('./#/profile'); await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await expect(page.getByRole('link', { name: 'Sign in', exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
