import { useEffect, useState } from 'react';
import { adminCustomBuilderApi } from '../../services/customBuilderApi';
import { customerError, money } from '../../utils/storefront';

const numberFields = ['minimumWidth', 'maximumWidth', 'widthStep', 'minimumHeight', 'maximumHeight', 'heightStep', 'minimumQuantity', 'maximumQuantity', 'quantityStep', 'pricePerSquareUnit', 'minimumLinePrice'];

export default function CustomBuilderConfig() {
  const [data, setData] = useState(null); const [draft, setDraft] = useState(null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [pending, setPending] = useState(false); const [testQuote, setTestQuote] = useState(null);
  const load = async () => { setError(''); try { const value = await adminCustomBuilderApi.getConfig(); setData(value); setDraft(structuredClone(value.draft)); } catch (requestError) { setError(customerError(requestError)); } };
  useEffect(() => { load(); }, []);
  const change = (field, value) => setDraft((current) => ({ ...current, [field]: numberFields.includes(field) ? Number(value) : value }));
  const changeOption = (index, field, value) => setDraft((current) => ({ ...current, options: current.options.map((option, optionIndex) => optionIndex === index ? { ...option, [field]: field === 'unitPriceAdjustment' || field === 'sortOrder' ? Number(value) : value } : option) }));
  const save = async () => { setPending(true); setError(''); try { const updated = await adminCustomBuilderApi.updateDraft(draft.id, draft); setDraft(updated); setNotice('Draft saved.'); } catch (requestError) { setError(customerError(requestError)); } finally { setPending(false); } };
  const publish = async () => { setPending(true); setError(''); try { await adminCustomBuilderApi.publish(draft.id); setNotice('Configuration published; a new draft was created.'); await load(); } catch (requestError) { setError(customerError(requestError)); } finally { setPending(false); } };
  const test = async () => { setPending(true); try { const first = (group) => draft.options.find((option) => option.group === group && option.isActive)?.code; setTestQuote(await adminCustomBuilderApi.testQuote(draft.id, { width: draft.minimumWidth, height: draft.minimumHeight, quantity: draft.minimumQuantity, shapeCode: first('Shape'), materialCode: first('Material'), finishCode: first('Finish'), fontCode: first('Font'), colourCode: first('Colour'), textAlignment: 'center' })); } catch (requestError) { setError(customerError(requestError)); } finally { setPending(false); } };
  if (!draft) return <div className="admin-page"><h2>Custom builder</h2><p>{error || 'Loading configuration…'}</p></div>;
  return <div className="admin-page">
    <div className="page-header"><div className="header-content"><div><h2>Custom builder configuration</h2><p>Draft version {draft.versionNumber}; published version {data.published?.versionNumber || 'none'}.</p></div><div className="action-buttons"><button className="btn btn-outline-primary" disabled={pending} onClick={test}>Test quote</button><button className="btn btn-primary" disabled={pending} onClick={save}>Save draft</button><button className="btn btn-success" disabled={pending} onClick={publish}>Publish</button></div></div></div>
    {error && <p className="out-of-stock-alert" role="alert">{error}</p>}{notice && <p className="badge-success" role="status">{notice}</p>}
    <section className="card"><div className="card-header"><h3 className="card-title">Limits and pricing</h3></div><div className="card-body add-product-form">
      <div className="form-row"><label>Measurement unit<input className="form-control" value={draft.measurementUnit} onChange={(event) => change('measurementUnit', event.target.value)} /></label><label>Currency<input className="form-control" maxLength="3" value={draft.currency} onChange={(event) => change('currency', event.target.value)} /></label></div>
      <div className="form-row">{numberFields.map((field) => <label key={field}>{field.replace(/([A-Z])/g, ' $1')}<input className="form-control" type="number" min="0" step={field.includes('Quantity') ? 1 : 0.01} value={draft[field]} onChange={(event) => change(field, event.target.value)} /></label>)}</div>
      <div className="form-row"><label><input type="checkbox" checked={draft.artworkRequired} onChange={(event) => change('artworkRequired', event.target.checked)} /> Artwork required</label><label><input type="checkbox" checked={draft.proofRequired} onChange={(event) => change('proofRequired', event.target.checked)} /> Proof required</label></div>
      <label>Internal notes<textarea className="form-control" maxLength="500" value={draft.internalNotes || ''} onChange={(event) => change('internalNotes', event.target.value)} /></label>
      {testQuote && <p className="badge-success">Test quote: {money(testQuote.subtotal)} ({testQuote.pricingVersion})</p>}
    </div></section>
    <section className="card"><div className="card-header"><h3 className="card-title">Customer options</h3><button className="btn btn-outline-primary" onClick={() => setDraft((current) => ({ ...current, options: [...current.options, { group: 'Shape', code: '', label: '', unitPriceAdjustment: 0, isActive: true, sortOrder: current.options.length }] }))}>Add option</button></div><div className="table-responsive"><table><thead><tr><th>Group</th><th>Code</th><th>Label</th><th>Per-unit adjustment</th><th>Active</th><th /></tr></thead><tbody>{draft.options.map((option, index) => <tr key={`${index}-${option.id || 'new'}`}><td><select className="form-control" value={option.group} onChange={(event) => changeOption(index, 'group', event.target.value)}>{['Shape', 'Material', 'Finish', 'Font', 'Colour'].map((group) => <option key={group}>{group}</option>)}</select></td><td><input className="form-control" value={option.code} onChange={(event) => changeOption(index, 'code', event.target.value)} /></td><td><input className="form-control" value={option.label} onChange={(event) => changeOption(index, 'label', event.target.value)} /></td><td><input className="form-control" type="number" min="0" step="0.01" value={option.unitPriceAdjustment || 0} onChange={(event) => changeOption(index, 'unitPriceAdjustment', event.target.value)} /></td><td><input type="checkbox" checked={option.isActive} onChange={(event) => changeOption(index, 'isActive', event.target.checked)} /></td><td><button className="btn btn-danger btn-sm" onClick={() => setDraft((current) => ({ ...current, options: current.options.filter((_, itemIndex) => itemIndex !== index) }))}>Remove</button></td></tr>)}</tbody></table></div></section>
    <section className="card"><div className="card-header"><h3 className="card-title">Version history</h3></div><div className="table-responsive"><table><thead><tr><th>Version</th><th>Status</th><th>Published</th></tr></thead><tbody>{data.versions.map((version) => <tr key={version.id}><td>{version.versionNumber}</td><td>{version.status}</td><td>{version.publishedAt ? new Date(version.publishedAt).toLocaleString() : '—'}</td></tr>)}</tbody></table></div></section>
  </div>;
}
