import {
  FiArchive,
  FiArrowLeft,
  FiArrowRight,
  FiBarChart2,
  FiBox,
  FiCheck,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiEdit3,
  FiEye,
  FiFacebook,
  FiFileText,
  FiHeart,
  FiHome,
  FiImage,
  FiInstagram,
  FiLayers,
  FiLock,
  FiLogOut,
  FiMail,
  FiMapPin,
  FiMenu,
  FiMinus,
  FiPackage,
  FiPause,
  FiPhone,
  FiPlay,
  FiPlus,
  FiRefreshCw,
  FiSearch,
  FiSettings,
  FiShoppingBag,
  FiSliders,
  FiStar,
  FiTag,
  FiTrash2,
  FiTruck,
  FiUser,
  FiUsers,
  FiX,
} from 'react-icons/fi';

const icons = {
  archive: FiArchive,
  arrow: FiArrowRight,
  arrowLeft: FiArrowLeft,
  bag: FiShoppingBag,
  chart: FiBarChart2,
  check: FiCheck,
  chevronDown: FiChevronDown,
  chevronLeft: FiChevronLeft,
  chevronRight: FiChevronRight,
  edit: FiEdit3,
  eye: FiEye,
  facebook: FiFacebook,
  file: FiFileText,
  heart: FiHeart,
  home: FiHome,
  image: FiImage,
  images: FiImage,
  instagram: FiInstagram,
  layers: FiLayers,
  lock: FiLock,
  logout: FiLogOut,
  mail: FiMail,
  mapPin: FiMapPin,
  menu: FiMenu,
  minus: FiMinus,
  package: FiPackage,
  pause: FiPause,
  phone: FiPhone,
  play: FiPlay,
  plus: FiPlus,
  refresh: FiRefreshCw,
  search: FiSearch,
  settings: FiSettings,
  sliders: FiSliders,
  star: FiStar,
  tag: FiTag,
  trash: FiTrash2,
  truck: FiTruck,
  user: FiUser,
  users: FiUsers,
  x: FiX,
};

export default function AppIcon({ name, title, ...props }) {
  const Component = icons[name] || FiBox;
  return <Component aria-hidden={title ? undefined : true} aria-label={title} focusable="false" {...props} />;
}
